server:
  port: 9017
spring:
  application:
    name: nacos-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://152.136.235.203:3306/lair?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      validation-query: select 1
      max-wait: 60000
      initial-size: 2
      max-active: 300
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
  cloud:
    nacos:
      discovery:
        cluster-name: nacos-payment-provider
        server-addr: 127.0.0.1:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bigbear.*.dao