server:
  port: 9010
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
#      routes:
#        - id: consumer-routh
      discovery:
        locator:
          enabled: true
eureka:
  instance:
    instance-id: provider-service-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka1:9004/eureka
      #      defaultZone: http://eureka1:9004/eureka,http://eureka2:9005/eureka
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
