server:
  port: 9007
spring:
  application:
    name: consumer-feign-service
eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka1:9004/eureka,http://eureka2:9005/eureka