server:
  port: 9003
spring:
  application:
    name: consumer-service

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:9004/eureka