server:
  port: 9003
spring:
  application:
    name: consumer-service

eureka:
  instance:
    instance-id: consumer-service-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka1:9004/eureka,http://eureka2:9005/eureka