server:
  port: 9011
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuydit/lair-config.git
          search-paths:
            - lair-provider-payment-9006
          default-label: main
          skip-ssl-validation: true
eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
#      defaultZone: http://eureka1:9004/eureka,http://eureka2:9005/eureka
      defaultZone: http://eureka1:9004/eureka